on:
  push:
    branches:
      "master"
name: Build
jobs:
  test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: 'docker.pkg.github.com'
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build Docker Image
        run: make docker
      - name: Push Docker Image (latest)
        run: make docker-push
        env:
          DOCKER_REMOTE_IMAGE: 'docker.pkg.github.com/mpliego-travelperk/travelperk-university-frontend/frontend:latest'