on:
  pull_request:
    branches:
      "master"
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Use Node.js 14.4.0
        uses: actions/setup-node@v1
        with:
          node-version: 14.4.0
      - name: Build Docker Image
        run: make dep test-ci